using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEditor.Animations;
using UnityEngine;

public static class AnimatorStateHashGenerator
{
    [MenuItem("Tools/Animation/Generate State Hash Class From Selected Controller")]
    private static void GenerateFromSelectedController()
    {
        if (Selection.activeObject is not AnimatorController controller)
        {
            EditorUtility.DisplayDialog(
                "No Animator Controller Selected",
                "Please select an AnimatorController asset in the Project window.",
                "OK");
            return;
        }

        var controllerPath = AssetDatabase.GetAssetPath(controller);
        var controllerFileName = Path.GetFileNameWithoutExtension(controllerPath);
        var className = SanitizeIdentifier(controllerFileName) + "States";

        var outputPath = EditorUtility.SaveFilePanelInProject(
            "Save generated state hash class",
            className + ".g.cs",
            "cs",
            "Choose where to save the generated file.");

        if (string.IsNullOrWhiteSpace(outputPath))
            return;

        var code = BuildCode(controller, className);

        File.WriteAllText(outputPath, code, new UTF8Encoding(false));
        AssetDatabase.Refresh();

        Debug.Log($"Generated animator state class: {outputPath}", controller);
    }

    private static string BuildCode(AnimatorController controller, string className)
    {
        var entries = new List<StateEntry>();

        foreach (var layer in controller.layers)
        {
            string layerName = layer.name;
            CollectStatesRecursive(
                stateMachine: layer.stateMachine,
                layerName: layerName,
                parentPath: "",
                entries: entries);
        }

        var sb = new StringBuilder();

        sb.AppendLine("// Generated by AnimatorStateHashGenerator.");
        sb.AppendLine("// Changes may be overwritten.");
        sb.AppendLine();
        sb.AppendLine("using UnityEngine;");
        sb.AppendLine();
        sb.AppendLine($"public static class {className}");
        sb.AppendLine("{");

        var byLayer = new Dictionary<string, List<StateEntry>>();
        foreach (var entry in entries)
        {
            if (!byLayer.TryGetValue(entry.LayerName, out var list))
            {
                list = new List<StateEntry>();
                byLayer[entry.LayerName] = list;
            }

            list.Add(entry);
        }

        foreach (var kvp in byLayer)
        {
            var layerClassName = SanitizeIdentifier(kvp.Key);
            sb.AppendLine($"    public static class {layerClassName}");
            sb.AppendLine("    {");

            var usedNames = new HashSet<string>();

            foreach (var entry in kvp.Value)
            {
                var memberBaseName = BuildMemberName(entry.SubStateMachinePath, entry.StateName);
                memberBaseName = MakeUnique(memberBaseName, usedNames);

                sb.AppendLine($"        public const string {memberBaseName} = \"{entry.FullPath}\";");
                sb.AppendLine($"        public static readonly int {memberBaseName}Hash = Animator.StringToHash({memberBaseName});");
                sb.AppendLine();
            }

            sb.AppendLine("    }");
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void CollectStatesRecursive(AnimatorStateMachine stateMachine, string layerName, string parentPath, List<StateEntry> entries)
    {
        foreach (var childState in stateMachine.states)
        {
            var stateName = childState.state.name;

            var subStatePath = parentPath;
            var fullPath = string.IsNullOrEmpty(subStatePath)
                ? $"{layerName}.{stateName}"
                : $"{layerName}.{subStatePath}.{stateName}";

            entries.Add(new StateEntry
            {
                LayerName = layerName,
                SubStateMachinePath = subStatePath,
                StateName = stateName,
                FullPath = fullPath
            });
        }

        foreach (var childStateMachine in stateMachine.stateMachines)
        {
            var childName = childStateMachine.stateMachine.name;
            var nextPath = string.IsNullOrEmpty(parentPath)
                ? childName
                : $"{parentPath}.{childName}";

            CollectStatesRecursive(
                childStateMachine.stateMachine,
                layerName,
                nextPath,
                entries);
        }
    }

    private static string BuildMemberName(string subStateMachinePath, string stateName)
    {
        if (string.IsNullOrEmpty(subStateMachinePath))
            return SanitizeIdentifier(stateName);

        return SanitizeIdentifier(subStateMachinePath.Replace('.', '_') + "_" + stateName);
    }

    private static string MakeUnique(string baseName, HashSet<string> usedNames)
    {
        var candidate = baseName;
        var suffix = 2;

        while (!usedNames.Add(candidate))
        {
            candidate = $"{baseName}_{suffix}";
            suffix++;
        }

        return candidate;
    }

    private static string SanitizeIdentifier(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
            return "_";

        var sb = new StringBuilder(value.Length);

        char first = value[0];
        if (char.IsLetter(first) || first == '_')
            sb.Append(first);
        else
            sb.Append('_');

        for (var i = 1; i < value.Length; i++)
        {
            char c = value[i];
            sb.Append(char.IsLetterOrDigit(c) || c == '_' ? c : '_');
        }

        return sb.ToString();
    }

    private sealed class StateEntry
    {
        public string LayerName;
        public string SubStateMachinePath;
        public string StateName;
        public string FullPath;
    }
}