// Generated by AnimatorStateHashGenerator.
// Changes may be overwritten.

using UnityEngine;

public static class EntityStates
{
    public static class Base_Layer
    {
        public const string Idle = "Base Layer.Idle";
        public static readonly int IdleHash = Animator.StringToHash(Idle);

        public const string Attack = "Base Layer.Attack";
        public static readonly int AttackHash = Animator.StringToHash(Attack);

    }
}
